### ISSUE TITLE
Control Net with OneFlow ?

### ISSUE THREAD

**Issue by abi98213** [Oneflow-Inc/onediff#127]
Hey,
Thanks for your awesome repo. Is it possible to run Controlnet with oneflow ?
If we would be able to it would be really fast and good for users
Thanks

**Comment by jackalcooper** [comment]
we are working on webgui support to enable drawing for controlnet

**Comment by mabdullahrafique** [comment]
When can we expect this for simple diffusers support ?

**Comment by mabdullahrafique** [comment]
@jackalcooper

**Comment by jackalcooper** [comment]
@doombeaker do you have a date for the release of webui?

**Comment by doombeaker** [comment]
> @doombeaker do you have a date for the release of webui?

Not yet. About 2~3 weeks later, we can give a release **plan**

**Comment by mabdullahrafique** [comment]
@doombeaker Can we get a faster release for simple diffusers ?

**Comment by mabdullahrafique** [comment]
@doombeaker @jackalcooper If you can please let us know

**Comment by Jackwensen** [comment]
> @doombeaker Can we get a faster release for simple diffusers ?

Thanks for your attention, we are working on it, hopefully this week.

**Comment by liuguicen** [comment]
> > @doombeaker Can we get a faster release for simple diffusers ?
> 
> Thanks for your attention, we are working on it, hopefully this week.

Great, look forward to it

**Comment by Jackwensen** [comment]
We support Control Net in our [onediff 0.7.0 version](https://pypi.org/project/onediff/), to use latest onediff we need to upgrade diffusers version to 0.14.0 using `python3 -m pip install "diffusers[torch]==0.14.0"` 
You can find the example in this [file](https://github.com/Oneflow-Inc/diffusers/blob/main/examples/control_net_canny.py), besides this canny example uses cv2 library, so we need to install opencv `pip install opencv-contrib-python`

**Comment by NicholasKao1029** [comment]
Hi is controlnet on the menu?

**Comment by NicholasKao1029** [comment]
@Hank0626 Very nice, works like a charm. There seems to be a significant performance hit by oneflow standards is there plans to mitigate this?

**Comment by strint** [comment]
Please update to the latest version: https://github.com/Oneflow-Inc/onediff?tab=readme-ov-file#install-from-source
This issue is too old to follow and will be closed. Feel free to reopen it and continue.
