### ISSUE TITLE
Embedding 

### ISSUE THREAD

**Issue by NicholasKao1029** [Oneflow-Inc/onediff#166]
Is there a method to load embeddings with oneflow?

**Comment by jackalcooper** [comment]
could you give us some code example? oneflow should be compatible with most of torch api

**Comment by NicholasKao1029** [comment]
![image](https://user-images.githubusercontent.com/45542006/227746896-502fb70f-b740-4ff6-aa84-b4b07ab28fe7.png)
This comes from this notebook https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/stable_conceptualizer_inference.ipynb#scrollTo=bJx50Ta37392 it's from diffusers themselves, it loads the `.bin` file into clip. 

I myself remember having issues importing CLIP and such

**Comment by NicholasKao1029** [comment]
Thanks @diagonalge I'll check this out appreciated

**Comment by NicholasKao1029** [comment]
@jackalcooper this PR for loading embeds has just got merged into `0.15.dev` for hugggingface
https://github.com/huggingface/diffusers/pull/2009

code snippet from diffusers looks like 
```
from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16)
pipe.load_textual_inversion("sd-concepts-library/low-poly-hd-logos-icons")
pipe.load_textual_inversion("./2911")
pipe.to("cuda")

image = pipe("An logo of a turtle in Style-Winter with <low-poly-hd-logos-icons>").images[0]
image.save("/home/patrick/images/a_tryout.png")
```

naturally doesn't work on oneflow pipeline right now. Do you think this is feasible to integrate into oneflow?

**Comment by NicholasKao1029** [comment]
> @jackalcooper this PR for loading embeds has just got merged into `0.15.dev` for hugggingface [huggingface/diffusers#2009](https://github.com/huggingface/diffusers/pull/2009)
> 
> code snippet from diffusers looks like
> 
> ```
> from diffusers import DiffusionPipeline
> import torch
> 
> pipe = DiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16)
> pipe.load_textual_inversion("sd-concepts-library/low-poly-hd-logos-icons")
> pipe.load_textual_inversion("./2911")
> pipe.to("cuda")
> 
> image = pipe("An logo of a turtle in Style-Winter with <low-poly-hd-logos-icons>").images[0]
> image.save("/home/patrick/images/a_tryout.png")
> ```
> 
> naturally doesn't work on oneflow pipeline right now. Do you think this is feasible to integrate into oneflow?

Following up to see if there is any chance this will be implemented soon!

**Comment by Hank0626** [comment]
@NicholasKao1029 You can now pull the lastest code of onediff, and try `load_textual_inversion` by the following code snippet. It's ok in my enviroment.
```python
import oneflow as flow
from onediff import OneFlowStableDiffusionPipeline as DiffusionPipeline

pipe = DiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=flow.float16)
pipe.load_textual_inversion("sd-concepts-library/low-poly-hd-logos-icons")
# pipe.load_textual_inversion("./2911") # I comment this line 
pipe.to("cuda")

image = pipe("An logo of a turtle in Style-Winter with <low-poly-hd-logos-icons>").images[0]
image.save("/home/patrick/images/a_tryout.png")
```

**Comment by NicholasKao1029** [comment]
It seems to work as in it changes the picture when the embedding is placed, however the changed image does not really have the "characteristics" of the embedding

**Comment by strint** [comment]
> It seems to work as in it changes the picture when the embedding is placed, however the changed image does not really have the "characteristics" of the embedding

That may be a problem caused by constant folding. The parameters in the graph are optimized by constant folding, and may not necessarily be bound to the parameters in the original eager module. 

So the parameters must be updated before the first pipe inference.

**Comment by NicholasKao1029** [comment]
Gotcha thanks will try this

**Comment by NicholasKao1029** [comment]
@strint Thanks for the tip this works great for`.bin` files.

however A111 `.pt` or `.safetensors` files are being read with no exception but there is no difference in output with or without the loading of the textual inversion

**Comment by NicholasKao1029** [comment]
@strint I've now tested with normal diffusers 0.15 `load_textual_inversion` works as expected and I can see the ti concept show up.
