### ISSUE TITLE
LoRA support in Diffusers version 0.10

### ISSUE THREAD

**Issue by Rizi2001** [Oneflow-Inc/onediff#168]
Hi, I'm using a local environment for OneFlow along with diffusers (OneFlow-fork. Locally cloned). I need LoRA support to infer my Stable Diffusion pipeline. I can't upgrade Diffusers version because of OneFlow dependencies. So I'm trying to in-corporate the dependencies of diffusers 0.12 into my existing 0.10 version so I can use LoRA support. Is there a solution for this? I'm stuck in the error "ImportError: cannot import name 'DEPRECATED_REVISION_ARGS' from diffusers.utils (__init__.py)", where as both the deprecation_utils are same, of Huggingface diffusers latest and oneflow-fork diffusers.
Looking for a solution for this.

**Comment by strint** [comment]
LoRA is supported now.

Please update to the latest version: https://github.com/Oneflow-Inc/onediff?tab=readme-ov-file#install-from-source

This issue is too old to follow and will be closed. Feel free to reopen it and continue.
