### ISSUE TITLE
Oneflow not  achieving the same performance with the new update

### ISSUE THREAD

**Issue by abi98213** [Oneflow-Inc/onediff#191]
Hey, 
We had created the python environment which was going good speed ( 30 it/sec ) on my 3090. The installed oneflow version was oneflow-0.9.1.dev20230212+cu117. And I was using oneflow-fork as diffusers branch. With the new update of oneflow the speed has considerably gone down on 3090 and 4090 but it is same on A100 GPU. 
I am not able to find oneflow-0.9.1.dev20230212+cu117 version anywhere to replicate the same speed on my local 3090 machine. 
So my question is why oneflow new version and onediff are not giving speed up on 4090 and 3090 machines.
Thank you very much

**Comment by abi98213** [comment]
@doombeaker If you can help please

**Comment by doombeaker** [comment]
thank you for you feedback. I will soon build and update the whl package of oneflow-0.9.1.dev20230212+cu117 and let related colleagues try to locate and solve the problems.

**Comment by doombeaker** [comment]
You can use the older version whl package first 

```
pip install -f https://oneflow-staging.oss-cn-beijing.aliyuncs.com/branch/rollback_20230212_sd_speed/cu117 --pre oneflow
```

**Comment by strint** [comment]
Please update to the latest version: https://github.com/Oneflow-Inc/onediff?tab=readme-ov-file#install-from-source
This issue is too old to follow and will be closed. Feel free to reopen it and continue.
