### ISSUE TITLE
如何使用oneflow在多机多卡下训练stablediffusion？

### ISSUE THREAD

**Issue by zhangvia** [Oneflow-Inc/onediff#205]
现在oneflow可以直接无缝将diffusers的训练stable diffusion代码直接切换到oneflow上吗

**Comment by doombeaker** [comment]
没有尝试过，理论上可以。你方便试试吗。如果有不对齐问题，欢迎反馈

**Comment by strint** [comment]
当前没有支持训练的计划，可能会考虑微调。
