### ISSUE TITLE
Does OneFlow have any work on parallel inference internally?

### ISSUE THREAD

**Issue by sanbuphy** [Oneflow-Inc/onediff#214]
For example, if I send requests simultaneously using the Gradio API, I can see that parallel inference is possible internally (although the overall time increases by a multiple of the number of requests). I want to debug this and I suspect that there might be a context manager automatically randomly allocating one request for inference during the iteration of inference sampling, and then constantly switching back and forth. However, the code inside is all bytecode operations, and I'm not quite sure how to debug it.Thank you very much.

**Comment by strint** [comment]
Here is a multi-process inference example: https://github.com/Oneflow-Inc/onediff/blob/main/examples/text_to_image_sdxl_mp_load.py

This issue is too old to follow and will be closed. Feel free to reopen it and continue.
