### ISSUE TITLE
Support for Token Merging and Flash attention(xformers) 

### ISSUE THREAD

**Issue by G-Prajwal** [Oneflow-Inc/onediff#222]
`pipe = pipe.to("cuda")`
`pipe.enable_xformers_memory_efficient_attention()`
`pipe.unet.to(memory_format=torch.channels_last)`
`tomesd.apply_patch(pipe, ratio=0.5)`

Currently Token Merging for stable diffusion(by tomesd) and enable former's aren't supported with inflow... 
Oneflow performance is very good without these optimisations and would like to see the performance with these optimisations. Will there be support for these optimisations in future?

**Comment by strint** [comment]
No need xformers because we have implemented the optimization in oneflow.

Please update to the latest version: https://github.com/Oneflow-Inc/onediff?tab=readme-ov-file#install-from-source

This issue is too old to follow and will be closed. Feel free to reopen it and continue.
