### ISSUE TITLE
怎么使用lora模型

### ISSUE THREAD

**Issue by xyfZzz** [Oneflow-Inc/onediff#223]
请问怎么基于oneflow使用lora模型，有相关使用文档吗？

**Comment by strint** [comment]
https://github.com/Oneflow-Inc/onediff/blob/main/examples/text_to_image_sdxl_lora.py

Please update to the latest version: https://github.com/Oneflow-Inc/onediff?tab=readme-ov-file#install-from-source

This issue is too old to follow and will be closed. Feel free to reopen it and continue.
