### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'lazy'

### ISSUE THREAD

**Issue by Pe4nutZz** [Oneflow-Inc/onediff#225]
![image](https://github.com/Oneflow-Inc/diffusers/assets/25875567/8f84ebb0-44ca-4646-adc8-029aa221f228)

**Comment by Hank0626** [comment]
Could please provide your `oneflow` version by:
```
python -m oneflow --doctor
```

**Comment by Pe4nutZz** [comment]
![image](https://github.com/Oneflow-Inc/diffusers/assets/25875567/efd9a409-c58f-47cd-b40e-44ee4f3a8591)

**Comment by Pe4nutZz** [comment]
> Could please provide your `oneflow` version by:
> 
> ```
> python -m oneflow --doctor
> ```

0.9.0

**Comment by Hank0626** [comment]
It's ok for me in my env.
Try
```
pip install -U onediff
```

Also, does this work for you:
```
python -c "import oneflow; oneflow.mock_torch.enable(lazy=True)"
```

**Comment by Pe4nutZz** [comment]
> pip install -U onediff
oneflow.int16 is not implemented现在又报这个错误了。。。。

**Comment by Hank0626** [comment]
看看完整报错栈

**Comment by Pe4nutZz** [comment]
> 看看完整报错栈

![image](https://github.com/Oneflow-Inc/diffusers/assets/25875567/ac5c855e-37d3-407b-b706-54cd86a7d7e7)

**Comment by Hank0626** [comment]
要不试试oneflow-nightly？
https://github.com/Oneflow-Inc/oneflow
这里有安装教程

**Comment by Pe4nutZz** [comment]
> 要不试试oneflow-nightly？ https://github.com/Oneflow-Inc/oneflow 这里有安装教程

好的好的，多谢，我试一下

**Comment by Amitg1** [comment]
Hi, installed Successfully installed oneflow-0.9.1.dev20230708+cu117, same issue:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[12], line 1
----> 1 from onediff import OneFlowStableDiffusionPipeline
      3 import oneflow as flow
      4 flow.mock_torch.enable()

File /opt/conda/lib/python3.9/site-packages/onediff/__init__.py:20
     14     return flow_randn(*args, **kwargs)
     17 flow.randn = dummy_randn
---> 20 flow.mock_torch.enable(lazy=True)
     21 import diffusers
     23 diffusers.utils.import_utils._accelerate_available = False

TypeError: __init__() got an unexpected keyword argument 'lazy'

**Comment by Xiangyu-CAS** [comment]
你好，一样的问题，“TypeError: enable.__init__() got an unexpected keyword argument 'lazy'”，怎么办呀

**Comment by strint** [comment]
请按照最新版本，现在按说没有相关问题了：https://github.com/Oneflow-Inc/onediff?tab=readme-ov-file#install-from-source
