### ISSUE TITLE
A10卡，速度慢于tensorrt

### ISSUE THREAD

**Issue by wangweilovelife** [Oneflow-Inc/onediff#226]
请教一下，oneflow挑卡吗？A10卡，oneflow运行sdcontrolnet需要2600ms，tensorrt只需要1300ms，参数设置一致，结果也一致，我看报告应该要比tensort快呀

`import cv2
from PIL import Image
import numpy as np

from onediff import OneFlowStableDiffusionControlNetPipeline

import oneflow as flow
flow.mock_torch.enable()

from diffusers.utils import load_image
from diffusers import ControlNetModel, EulerAncestralDiscreteScheduler

import time

image = load_image(
    "https://paddlenlp.bj.bcebos.com/models/community/junnyu/develop/control_bird_canny_demo.png"
)

image = np.array(image)

low_threshold = 100
high_threshold = 200

image = cv2.Canny(image, low_threshold, high_threshold)
image = image[:, :, None]
image = np.concatenate([image, image, image], axis=2)
canny_image = Image.fromarray(image)

controlnet = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-canny", torch_dtype=flow.float16)
    
pipe = OneFlowStableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", controlnet=controlnet, torch_dtype=flow.float16
)
pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(pipe.scheduler.config)

pipe.to("cuda")

generator = flow.manual_seed(1000)

prompt = "yellow,a bird, best quality, extremely detailed"
negative_prompt = "blurry, poor quality, painting, worst quality, lowres, low quality"

tic = time.perf_counter()
out_images = pipe(
    prompt = prompt, negative_prompt=negative_prompt, num_inference_steps=20, generator=generator, image=canny_image,
    height=512,
    width =512,
    guidance_scale=7.5,).images

toc = time.perf_counter()

print('| {:^10} | {:>9.2f} ms |'.format('Pipeline', (toc - tic)*1000.))

for i, image in enumerate(out_images):
    image.save(f"./output/{prompt}-of-{i}.png")

`

**Comment by Hank0626** [comment]
onediff的ControlNet应该还没有加入图优化；请问你有测试过其他的pipeline吗（比如text2img），性能如何？

**Comment by wangweilovelife** [comment]
> onediff的ControlNet应该还没有加入图优化；请问你有测试过其他的pipeline吗（比如text2img），性能如何？
目前想用controlnet，然后from onediff import OneFlowStableDiffusionControlNetPipeline也成功了，原来是没优化～其他pipeline还没测试，倒是可以试试

**Comment by hjchen2** [comment]
最新版本在A10上有比较大的优化，可以下载安装重新跑一下。安装命令，
```shell
python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu121
```
