### ISSUE TITLE
对于新模型如何实现加速呢

### ISSUE THREAD

**Issue by Pe4nutZz** [Oneflow-Inc/onediff#227]
damo/multi-modal_chinese_stable_diffusion_v1.0，比如对于阿里的这个模型直接套用加速生成的都是全黑的图了

**Comment by strint** [comment]
当前没有提供对定制模型的优化，的确可能会遇到问题。

如果有很强需求，请联系我们。

This issue is too old to follow and will be closed. Feel free to reopen it and continue.
