### ISSUE TITLE
你好，请问下，我将sd1.5的vae换成了sd-vae-ft-mse (https://huggingface.co/stabilityai/sd-vae-ft-mse),参数不匹配

### ISSUE THREAD

**Issue by cjt222** [Oneflow-Inc/onediff#228]
你好，请问下，我将sd1.5的vae换成了sd-vae-ft-mse (https://huggingface.co/stabilityai/sd-vae-ft-mse)，两个模型结构是一样的，但是加载VAE模型的时候发现有些参数没加载进去，报了如下信息：Some weights of the model checkpoint at ./models/vae were not used when initializing AutoencoderKL: ['encoder.mid_block.attentions.0.to_v.weight', 'decoder.mid_block.attentions.0.to_q.bias', 'decoder.mid_block.attentions.0.to_q.weight', 'decoder.mid_block.attentions.0.to_v.bias', 'encoder.mid_block.attentions.0.to_q.bias', 'encoder.mid_block.attentions.0.to_out.0.weight', 'decoder.mid_block.attentions.0.to_k.bias', 'encoder.mid_block.attentions.0.to_v.bias', 'encoder.mid_block.attentions.0.to_k.bias', 'decoder.mid_block.attentions.0.to_k.weight', 'encoder.mid_block.attentions.0.to_k.weight', 'decoder.mid_block.attentions.0.to_v.weight', 'encoder.mid_block.attentions.0.to_out.0.bias', 'encoder.mid_block.attentions.0.to_q.weight', 'decoder.mid_block.attentions.0.to_out.0.bias', 'decoder.mid_block.attentions.0.to_out.0.weight']
这个是什么原因

**Comment by strint** [comment]
请更新到最新的版本，最新版本提供了更高的灵活性。
