### ISSUE TITLE
Support for sdxl

### ISSUE THREAD

**Issue by abi98213** [Oneflow-Inc/onediff#229]
Hey, 
When is sdxl getting supported with oneflow
Thanks

**Comment by abi98213** [comment]
@sharpmark @Hank0626 @strint If you can please answer
Thanks

**Comment by anujnayyar1** [comment]
+1 for this would be super helpful

**Comment by artisan323** [comment]
+1

**Comment by shabri-arrahim** [comment]
+1

**Comment by strint** [comment]
Supporting for SDXL is released: https://github.com/Oneflow-Inc/diffusers/blob/main/examples/text_to_image_sdxl.py

Ref: https://github.com/Oneflow-Inc/diffusers/releases/tag/0.11.0
