### ISSUE TITLE
safetensors文件格式支持

### ISSUE THREAD

**Issue by Amber0130** [Oneflow-Inc/onediff#231]
可以添加对safetensors文件格式的支持吗？

**Comment by zengjie617789** [comment]
diffusers 也是到后面的版本才更新直接读取load_safetensors的；折衷方法是使用高版本的diffusers读取safetensors，将读取后的pipe保存成diffusers文件夹形式；亲测，可以使用。

**Comment by strint** [comment]
当前应该不存在这个问题了。

This issue is too old to follow and will be closed. Feel free to reopen it and continue.
