### ISSUE TITLE
flow.mock_torch.enable(lazy=True) TypeError: init() got an unexpected keyword argument 'lazy'

### ISSUE THREAD

**Issue by Chris-Ski** [Oneflow-Inc/onediff#246]
Trying to get this to work for the past 3 days :( I did a fresh install of Ubuntu 20.04 , and tried Python 3.8 and 3.10 nothing worked :( ... please help....

Dont matter what I done, I have same comunicat:

Traceback (most recent call last):
File "examples/text_to_image.py", line 1, in
from onediff import OneFlowStableDiffusionPipeline
File "/usr/local/lib/python3.8/dist-packages/onediff/init.py", line 20, in
flow.mock_torch.enable(lazy=True)
TypeError: init() got an unexpected keyword argument 'lazy'

Graphic Card RTX 3090
Cuda 11.7
Drivers 515.43.04

Oneflow installed : python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu117
"torch" "transformers==4.27.1" "diffusers[torch]==0.15.1"

![263705169-ff777519-1d03-472f-aea1-8f2fb3fff682](https://github.com/Oneflow-Inc/diffusers/assets/104285717/be0504d0-712f-45a4-b239-7b3cc874b374)

![263705196-bbf0d9ef-d1c0-4742-b173-3936709c85fb](https://github.com/Oneflow-Inc/diffusers/assets/104285717/49010106-1949-40bf-85a1-9f2cf0dfafb9)

![263705208-5578f296-87fe-4e19-9acb-0b3a6794bc50](https://github.com/Oneflow-Inc/diffusers/assets/104285717/97acc2ca-43c3-48d2-b3b5-b2a6997e2942)

![263705963-6aa84a8c-b84e-4807-9f92-9cbd759b1786](https://github.com/Oneflow-Inc/diffusers/assets/104285717/2c0e2972-d640-446c-8d7f-b68c1bda8071)

any idea whats wrong ??

**Comment by zengjie617789** [comment]
pull the latest source code of oneflow which contains the lazy keyword.
However, it meet another problem that oneflow has no attribute randn.

**Comment by jackalcooper** [comment]
seems like you are not installing nightly oneflow. could you try to install it with 
```py
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu117
```

**Comment by jackalcooper** [comment]
Note
the link https://staging.oneflow.info/branch/master/cu117 is not working now, please use the link I just posted in the comment above
