### ISSUE TITLE
显存逐渐变大

### ISSUE THREAD

**Issue by Amber0130** [Oneflow-Inc/onediff#274]
@strint  你好，目前我编译成静态图，放到线上使用，发现了占用显存会逐渐的增大这是什么原因？

**Comment by strint** [comment]
> @strint 你好，目前我编译成静态图，放到线上使用，发现了占用显存会逐渐的增大这是什么原因？

这不是一个已知的问题，我们之前实验显存是稳定的。可以使用下最新版本，看看现在问题还存在吗？
