### ISSUE TITLE
Comfyui image doesn't exist

### ISSUE THREAD

**Issue by Jongulo** [Oneflow-Inc/onediff#278]
On the wiki page for running comfyui with onediff you cannot pull the docker image since it doesn't exist.

**Comment by tommitytom** [comment]
Also having this issue. The actual error:
```
$ docker pull oneflowinc/comfyui-onediff:latest
Error response from daemon: pull access denied for oneflowinc/comfyui-onediff, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by Jongulo** [comment]
> Also having this issue. The actual error:
> 
> ```
> $ docker pull oneflowinc/comfyui-onediff:latest
> Error response from daemon: pull access denied for oneflowinc/comfyui-onediff, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
> ```

Yes you can check the oneflow docker hub and it isn't there
https://hub.docker.com/u/oneflowinc

**Comment by jackalcooper** [comment]
it has not been made public yet

**Comment by Jongulo** [comment]
> it has not been made public yet

Any estimated time when it will be made public?

**Comment by ConstantEgo** [comment]
I can confirm the problem.

**Comment by strint** [comment]
This issue is too old to follow and will be closed. Feel free to reopen it and continue.
