### ISSUE TITLE
Loading LORA with SDXL error

### ISSUE THREAD

**Issue by SameetAsadullah** [Oneflow-Inc/onediff#299]
Hey, I am trying to load LORA and then compile the graph but it throws the following error:

[ERROR](GRAPH:UNetGraph_0:UNetGraph) building graph got error.
  0%|                                                                                                                                                                                                    | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/sameet/oneflow/test.py", line 16, in <module>
    result = pipe(
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 814, in __call__
    noise_pred = self.unet(
  File "/home/sameet/oneflow/diffusers/src/onediff/infer_compiler/with_oneflow_compile.py", line 88, in __call__
    output = self._dpl_graph(*mapped_args, **mapped_kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 281, in __call__
    return self._dynamic_input_graph_cache(*args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/cache.py", line 115, in __call__
    return graph(*args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 284, in __call__
    self._compile(*args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 852, in _compile
    return self._compile_new(*args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 871, in _compile_new
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1374, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1491, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/home/sameet/oneflow/diffusers/src/onediff/infer_compiler/with_oneflow_compile.py", line 41, in build
    return self.unet(*args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 236, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 915, in forward
    sample, res_samples = downsample_block(
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 236, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 996, in forward
    hidden_states = attn(
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 236, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 292, in forward
    hidden_states = block(
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 236, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 155, in forward
    attn_output = self.attn1(
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 236, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/sameet/oneflow/diffusers/src/onediff/infer_compiler/attention_processor_1f.py", line 360, in forward
    return self.processor(
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/proxy.py", line 236, in __block_forward
    result = unbound_forward_of_module_instance(self, *args, **kwargs)
  File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/modules/module.py", line 200, in forward
    raise NotImplementedError()
NotImplementedError

Is it not implemented yet or am I doing anything wrong ?

**Comment by Amitg1** [comment]
Hi @SameetAsadullah, can you please share your code?
I'm also interested in figuring this out

**Comment by SameetAsadullah** [comment]
Hey @Amitg1. Thank you for replying. Here is the code:
```
from onediff.infer_compiler import oneflow_compile
from diffusers import DiffusionPipeline

pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, use_safetensors=True, variant="fp16")
pipe.load_lora_weights("Linaqruf/pastel-anime-xl-lora", weight_name="pastel-anime-xl.safetensors")
pipe.to("cuda")

pipe.unet = oneflow_compile(pipe.unet)
for i in range(2):
    result = pipe(
        prompt="A young beautiful girl",
        height=1024,
        width=1024,
        num_inference_steps=50
    ).images[0]

pipe.unet.save_graph("sdxl_graph_compiled")
```

**Comment by Amitg1** [comment]
Maybe it needed fusing before compiling?
https://huggingface.co/docs/diffusers/training/lora#fusing-lora-parameters

**Comment by strint** [comment]
> Hey, I am trying to load LORA and then compile the graph but it throws the following error:
> 
> ERROR building graph got error. 0%| | 0/50 [00:00<?, ?it/s] Traceback (most recent call last): 
> File "/home/sameet/oneflow/test.py", line 16, in result = pipe( File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) 
> File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 814, in **call** noise_pred = self.unet( 

## calling unet compile
> File "/home/sameet/oneflow/diffusers/src/onediff/infer_compiler/with_oneflow_compile.py", line 88, in **call** output = self._dpl_graph(*mapped_args, **mapped_kwargs) 
> File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 281, in **call** return self._dynamic_input_graph_cache(*args, **kwargs) 
> File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/cache.py", line 115, in **call** return graph(*args, **kwargs) 
> File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 284, in **call** self._compile(*args, **kwargs) 

## calling downsample_block
> File "/home/sameet/oneflow/diffusers/src/onediff/infer_compiler/w
> File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 915, in forward sample, res_samples = downsample_block( 

## calling attn
> File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 996, in forward hidden_states = attn( 

## calling block and attn1
> File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 292, in forward hidden_states = block( 
> File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 155, in forward attn_output = self.attn1( 

## calling processor
> File "/home/sameet/oneflow/diffusers/src/onediff/infer_compiler/attention_processor_1f.py", line 360, in forward return self.processor( 
> File "/home/sameet/oneflow/venv/lib/python3.10/site-packages/oneflow/nn/modules/module.py", line 200, in forward raise NotImplementedError() NotImplementedError

It seems that `self.processor` does not have a `forward` function?

**Comment by strint** [comment]
We have update the new main.

**Comment by wuyanzhang** [comment]
> We have updated the new main, you can try it to see if anything changed.

我更新到最新的代码了 还是会有上面的报错

**Comment by strint** [comment]
> > We have updated the new main, you can try it to see if anything changed.
> 
> 我更新到最新的代码了 还是会有上面的报错

你用的 lora 代码有公开的地址么

**Comment by hjchen2** [comment]
onediff has not support diffusers lora attention processor, fusing weight before use oneflow_compile should be ok.

**Comment by strint** [comment]
SDXL lora [example](https://huggingface.co/docs/diffusers/training/lora#stable-diffusion-xl:~:text=cuda%22)%0Apipe.-,load_lora_weights,-(lora_model_id)%0Aimage%20%3D%20pipe)


## no fusion example
```
pipe = StableDiffusionPipeline.from_pretrained(base_model_id, torch_dtype=torch.float16, use_safetensors=True)
pipe = pipe.to("cuda")
pipe.load_lora_weights(lora_model_id)
image = pipe("A picture of a sks dog in a bucket", num_inference_steps=25).images[0]
```

## fusion example
https://huggingface.co/docs/diffusers/training/lora#fusing-lora-parameters

@ccssu  Create a example of lora( fusion and no fusioin), try to reproduce the error in this issue and fix it.

**Comment by wuyanzhang** [comment]
import os
import argparse

import oneflow as flow
import torch

from onediff.infer_compiler import oneflow_compile
from onediff import EulerDiscreteScheduler, rewrite_self_attention
from diffusers import StableDiffusionXLPipeline


# SDXL base: StableDiffusionXLPipeline
scheduler = EulerDiscreteScheduler.from_pretrained("text2img_ckpt/stable-diffusion-xl-base-1.0", subfolder="scheduler")
base = StableDiffusionXLPipeline.from_pretrained(
    "text2img_ckpt/stable-diffusion-xl-base-1.0",
    scheduler=scheduler,
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True,
)

base.load_lora_weights("lora/", weight_name="pixel-art-xl-v1.1.safetensors")
base.to("cuda")

print("unet is compiled to oneflow.")
rewrite_self_attention(base.unet)
base.unet = oneflow_compile(base.unet)

image = base(
    prompt="closeup portrait of a woman in a kitchen by william eggleston, beautiful",
    height=1024,
    width=1024,
    num_inference_steps=30,
    num_images_per_prompt=1,
    output_type="pil",
).images
这是代码，用的公开的

**Comment by wuyanzhang** [comment]
`import os
import argparse

import oneflow as flow
import torch

from onediff.infer_compiler import oneflow_compile
from onediff import EulerDiscreteScheduler, rewrite_self_attention
from diffusers import StableDiffusionXLPipeline


# SDXL base: StableDiffusionXLPipeline
scheduler = EulerDiscreteScheduler.from_pretrained("/data/wuyz/weights/text2img_ckpt/stable-diffusion-xl-base-1.0", subfolder="scheduler")
base = StableDiffusionXLPipeline.from_pretrained(
    "/data/wuyz/weights/text2img_ckpt/stable-diffusion-xl-base-1.0",
    scheduler=scheduler,
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True,
)

base.load_lora_weights("/data/wuyz/weights/lora/", weight_name="pixel-art-xl-v1.1.safetensors")
base.fuse_lora(lora_scale=1)

# # LoRA two.
# base.load_lora_weights("/data/wuyz/weights/lora/", weight_name="wegg.safetensors")
# base.fuse_lora(lora_scale=1)

base.to("cuda")

# print("unet is compiled to oneflow.")
# rewrite_self_attention(base.unet)
# base.unet = oneflow_compile(base.unet)

import time
t0 = time.time()
image = base(
    prompt="closeup portrait of a woman in a kitchen by william eggleston, beautiful",
    height=1024,
    width=1024,
    num_inference_steps=30,
    num_images_per_prompt=1,
    output_type="pil",
).images`

**Comment by wuyanzhang** [comment]
`python
import os
import argparse

import oneflow as flow
import torch

from onediff.infer_compiler import oneflow_compile
from onediff import EulerDiscreteScheduler, rewrite_self_attention
from diffusers import StableDiffusionXLPipeline


# SDXL base: StableDiffusionXLPipeline
scheduler = EulerDiscreteScheduler.from_pretrained("/data/wuyz/weights/text2img_ckpt/stable-diffusion-xl-base-1.0", subfolder="scheduler")
base = StableDiffusionXLPipeline.from_pretrained(
    "/data/wuyz/weights/text2img_ckpt/stable-diffusion-xl-base-1.0",
    scheduler=scheduler,
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True,
)

base.load_lora_weights("/data/wuyz/weights/lora/", weight_name="pixel-art-xl-v1.1.safetensors")
base.fuse_lora(lora_scale=1)

# # LoRA two.
# base.load_lora_weights("/data/wuyz/weights/lora/", weight_name="wegg.safetensors")
# base.fuse_lora(lora_scale=1)

base.to("cuda")

# print("unet is compiled to oneflow.")
# rewrite_self_attention(base.unet)
# base.unet = oneflow_compile(base.unet)

import time
t0 = time.time()
image = base(
    prompt="closeup portrait of a woman in a kitchen by william eggleston, beautiful",
    height=1024,
    width=1024,
    num_inference_steps=30,
    num_images_per_prompt=1,
    output_type="pil",
).images
`

**Comment by wuyanzhang** [comment]
> > > We have updated the new main, you can try it to see if anything changed.
> > 
> > 
> > 我更新到最新的代码了 还是会有上面的报错
> 
> 你用的 lora 有公开的代码么，估计需要用代码复现下看看

```python
import os
import argparse

import oneflow as flow
import torch

from onediff.infer_compiler import oneflow_compile
from onediff import EulerDiscreteScheduler, rewrite_self_attention
from diffusers import StableDiffusionXLPipeline

scheduler = EulerDiscreteScheduler.from_pretrained("text2img_ckpt/stable-diffusion-xl-base-1.0", subfolder="scheduler")
base = StableDiffusionXLPipeline.from_pretrained(
    "text2img_ckpt/stable-diffusion-xl-base-1.0",
    scheduler=scheduler,
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True,
)

base.load_lora_weights("lora/", weight_name="pixel-art-xl-v1.1.safetensors")
base.to("cuda")

print("unet is compiled to oneflow.")
rewrite_self_attention(base.unet)
base.unet = oneflow_compile(base.unet)

image = base(
    prompt="closeup portrait of a woman in a kitchen by william eggleston, beautiful",
    height=1024,
    width=1024,
    num_inference_steps=30,
    num_images_per_prompt=1,
    output_type="pil",
).images
```
这是代码，用的公开的

**Comment by strint** [comment]
@SameetAsadullah @wuyanzhang @Amitg1  Please try the new main branch, it is fixed.

Note that:
- fusion Lora is preferred
- no fusion will affect the performance, and we are working on it.

**Comment by strint** [comment]
LoRA example is released： https://github.com/Oneflow-Inc/diffusers/blob/d62abe2b94ab7c78853d5586ba80bf45905e31ad/examples/text_to_image_sdxl_lora.py#L9
