### ISSUE TITLE
使用最新的镜像运行text_to_image.py报错

### ISSUE THREAD

**Issue by Mr-Jin2** [Oneflow-Inc/onediff#331]
ValueError: The component <class 'transformers.models.clip.image_processing_clip.CLIPImageProcessor'> of <class 'diffusers_extra.pipelines.stable_diffusion.pipeline_stable_diffusion_lpw.StableDiffusionLongPromptWeightingPipeline'> cannot be loaded as it does not seem to have any of the loading methods defined in {'ModelMixin': ['save_pretrained', 'from_pretrained'], 'SchedulerMixin': ['save_pretrained', 'from_pretrained'], 'DiffusionPipeline': ['save_pretrained', 'from_pretrained'], 'OnnxRuntimeModel': ['save_pretrained', 'from_pretrained'], 'PreTrainedTokenizer': ['save_pretrained', 'from_pretrained'], 'PreTrainedTokenizerFast': ['save_pretrained', 'from_pretrained'], 'PreTrainedModel': ['save_pretrained', 'from_pretrained'], 'FeatureExtractionMixin': ['save_pretrained', 'from_pretrained'], 'ProcessorMixin': ['save_pretrained', 'from_pretrained'], 'ImageProcessingMixin': ['save_pretrained', 'from_pretrained'], 'ORTModule': ['save_pretrained', 'from_pretrained'], 'ZHCLIPTextEncoderWithTransformation': ['save_pretrained', 'from_pretrained'], 'StableDiffusionLongPromptWeightingPipeline': ['save_pretrained', 'from_pretrained'], 'CLIPTextModelWithChannelProjection': ['save_pretrained', 'from_pretrained'], 'CustomStableDiffusionSafetyChecker': ['save_pretrained', 'from_pretrained'], 'BaichuanTokenizer': ['save_pretrained', 'from_pretrained'], 'BaichuanModel': ['save_pretrained', 'from_pretrained']}.
另外，日志也有问题，这里的torch似乎应该指的是oneflow
You are using torch==0.9.1+cu121.git.c9b6f23, but torch>=1.10.0 is required to use BridgeTowerModel. Please upgrade torch. Loading custom CUDA kernels... Could not load the custom kernel for multi-scale deformable attention: No module named 'MultiScaleDeformableAttention' Discovered apex.normalization.FusedRMSNorm - will use it instead of LongT5LayerNorm You are using torch==0.9.1+cu121.git.c9b6f23, but torch>=1.9.0 is required to use MCTCTModel. Please upgrade torch. You are using torch==0.9.1+cu121.git.c9b6f23, but torch>=1.10.0 is required to use ViltModel. Please upgrade torch.

**Comment by hjchen2** [comment]
如果安装了xformers，确实是会导致version相关的报错，你可以检查一下你的环境，如果安装了就请先uninstall之后再试一下。我们内部正在修复这个问题。

**Comment by Mr-Jin2** [comment]
没安装xformers，是from onediff.infer_compiler import oneflow_compile导致的

**Comment by strint** [comment]
···
oneflow --pre -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/master_open_source/cu121
transformers==4.27.1
diffusers[torch]==0.19.3
onediff
chardet
opencv-python==4.8.0.74
```

可以对下这些版本是否正确
