### ISSUE TITLE
你好，请问oneflow的sd xl如何构建动态分辨率的输入，我按照例子，compile后改变输入尺寸，就会报卷积算子输入维度不匹配的错误

### ISSUE THREAD

**Issue by cjt222** [Oneflow-Inc/onediff#337]

**Comment by hjchen2** [comment]
请问你跑的是我们提供的text_to_image_sdxl.py这个例子么，我自己测试改变分辨率是没有问题的。我们目前不支持改变batch size，你可以检查一下是不是同时改了batch size了。

**Comment by cjt222** [comment]
是的，我改变了batch size，这个什么时候会修复呢？

**Comment by hjchen2** [comment]
> 是的，我改变了batch size，这个什么时候会修复呢？

你好，按计划我们会在最近一周修复

**Comment by strint** [comment]
参考这里：https://github.com/Oneflow-Inc/onediff/issues/432#issuecomment-1859751584
