### ISSUE TITLE
使用register注册新类时会卡死

### ISSUE THREAD

**Issue by zhangvia** [Oneflow-Inc/onediff#384]
当我用register来注册一个新的类，希望能够加速时。torch转flow的过程中，卡在了onediff_mock_torch这个上下文管理器的    with flow.mock_torch.enable(lazy=True,verbose=True):
        yield
这句话中。
使用register注册新的包，是有什么要求吗。我的新的包目录结构如下：
![image](https://github.com/Oneflow-Inc/diffusers/assets/38352569/0800789d-8dd9-4c1d-9842-5996f637caaf)

在__init__.py中导出了需要使用的几个模型类

**Comment by zhangvia** [comment]
@strint 在进一步debug后发现，类似下面这样的类：
![image](https://github.com/Oneflow-Inc/diffusers/assets/38352569/873e7562-a098-4cdc-9d0d-bdfa609eeb1e)
在转换之后，貌似仅转换了sequential中的每一个module，而没有转换继承了sequential的TimestepEmbedSequential类。实际执行到这个自定义类的时，forward函数会直接调用oneflow.nn.utils.container.py中的get_seq的forward函数，而不是自定义类中重写的forward函数。

最后定位到@torch2oflow.register
def _(mod: torch.nn.Sequential, verbose=True)这个函数里，发现转换sequential时是新建flow.nn.Sequential类，把转换后的module放进去，而不是直接转换自定义的sequential类。是不能转换吗？

**Comment by strint** [comment]
> 最后定位到@torch2oflow.register def _(mod: torch.nn.Sequential, verbose=True)这个函数里，发现转换sequential时是新建flow.nn.Sequential类，把转换后的module放进去，而不是直接转换自定义的sequential类。是不能转换吗？

@ccssu

**Comment by ccssu** [comment]
这个sequential时是新建flow.nn.Sequential类 是 onediff 版本过老了，请更新下onediff  @zhangvia  
最新的Sequential相关代码如下：
https://github.com/Oneflow-Inc/diffusers/blob/cc844a46749a4c988cbc759783648e63e8f59b85/src/onediff/infer_compiler/transform/builtin_transform.py#L248-L256C22

<img width="845" alt="image" src="https://github.com/Oneflow-Inc/diffusers/assets/109639975/ceaf9065-45bb-45d5-8caf-1d0523615d57">

**Comment by zhangvia** [comment]
> 这个sequential时是新建flow.nn.Sequential类 是 onediff 版本过老了，请更新下onediff @zhangvia 最新的Sequential相关代码如下： https://github.com/Oneflow-Inc/diffusers/blob/cc844a46749a4c988cbc759783648e63e8f59b85/src/onediff/infer_compiler/transform/builtin_transform.py#L248-L256C22
> 
> <img alt="image" width="845" src="https://private-user-images.githubusercontent.com/109639975/287584652-ceaf9065-45bb-45d5-8caf-1d0523615d57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NjE5MTYsIm5iZiI6MTcwMTY2MTYxNiwicGF0aCI6Ii8xMDk2Mzk5NzUvMjg3NTg0NjUyLWNlYWY5MDY1LTQ1YmItNDVkNS04Y2FmLTFkMDUyMzYxNWQ1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQwMzQ2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTUxMzYyYWRiNGM5NDAwMzdjNDdjZTNjYjk1OTA2ZDM2M2NjMzhmMTZmMTUwYWMyMmY1MGIxZTU4YzNkMWUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kUpYJKayZbXyx8J4fdo2_POvDX-3xb6_ZaBBMDSTkME">

好的，谢谢，我更新一下试试，

**Comment by zhangvia** [comment]
我测试了一下，这个问题解决了。但是在自定义的池化，卷积函数出现了其他问题。模型定义中包含了一些类似以下的函数定义：
![image](https://github.com/Oneflow-Inc/diffusers/assets/38352569/01ab38da-1e57-40f5-9a98-ab3d1b503d67)
这些函数返回了具体的nn类，但是使用register注册整个文件夹时，并未修改这些函数返回的类。这是需要在torch2oflow_funcs参数内填写具体要转换的函数吗？填写后，mock出来的文件夹下的类会自动引用转换后的函数吗

**Comment by strint** [comment]
这里有个特殊处理

https://github.com/Oneflow-Inc/diffusers/blob/2f6aeb8c703f95abef85485bc6a949a22efe410c/src/onediff/infer_compiler/transform/builtin_transform.py#L109C24-L109C24

你试着改下这里，改成如下试试：
```
        elif (
            isinstance(self._oflow_proxy_submod, (torch.nn.Conv2d, torch.nn.Conv3d, torch.nn.AvgPool1d, torch.nn.AvgPool2d, torch.nn.AvgPool3d))
            and attribute == "channel_pos"
        ):
            return "channels_first"
```

**Comment by zhangvia** [comment]
这个应该是转换时的问题吧，我看了下pooling.py的源码，divisor_override默认是0.我的模型定义代码部分，定义AvgPool2d时也并没有传入divisor_override

**Comment by strint** [comment]
是的，这里估计是那个 divisor_override 的参数没对齐，需要结合你的 case debug 对齐下。

社区版我们暂时精力都集中在支持 diffusers / comfyui / sd-web-ui 这些主流库的编译加速。

其它自定义库会响应慢一些，需要社区的小伙伴自己先做下尝试。如果您那边需要按商业标准支持，尽快定制完成，请参考这里联系进行商务合作适配：https://github.com/Oneflow-Inc/diffusers#business-inquiry-on-onediff-enterprise-edition
