### ISSUE TITLE
使用oneflow_compiler编译自定义类时出现参数名不匹配

### ISSUE THREAD

**Issue by zhangvia** [Oneflow-Inc/onediff#385]
我使用oneflow_compiler来编译了https://github.com/ankanbhunia/PIDM 这个仓库中的models文件夹下的unet_autoenc.py中的BeatGANsAutoencModel模型。但在build_graph时在前向过程的230行（unet_autoenc.py）的模型的input_blocks出现了forward() got an unexpected keyword argument 'emb'错误。input_blocks是一个TimestepEmbedSequential类，定义在blocks.py中。该类会根据运行时实际使用的层来调用不同的层的forward函数。
是否有可能torch转flow时的转换操作，使得这里TimestepEmbedSequential在判断容器内层的类型时出错了，所以导致参数类型错误？这里判断容器内网络层的类型代码如下：
![image](https://github.com/Oneflow-Inc/diffusers/assets/38352569/69303a5c-66f8-4543-9035-ecab3033f88c)

**Comment by strint** [comment]
抱歉，暂时我们没有投入支持自定义模型。
