### ISSUE TITLE
Segmentation fault (Address not mapped to object [(nil)])

### ISSUE THREAD

**Issue by ErwannMillon** [Oneflow-Inc/onediff#393]
### Description

Getting this error frequently when running a compiled diffusers UNet, any suggestions?

**Comment by strint** [comment]
@ErwannMillon 

We need more info to figure this out:
1. The full error stack info

2. The oneflow version:
```
python -m oneflow --doctor
```
3. The diffusers version:
```
pip list | grep diffusers
```
4. The OneDiff commit id

**Comment by ErwannMillon** [comment]
1. No stack trace, just 
2. 
version: 0.9.1+cu121.git.c9b6f23
git_commit: c9b6f23
cmake_build_type: Release
rdma: True
mlir: True

3. 
diffusers version: 0.24.0.dev0

4. 
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off | 00000000:00:04.0 Off |                    0 |
| N/A   32C    P0              48W / 400W |  15871MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      4151      C   /usr/bin/python3                          15862MiB |
+---------------------------------------------------------------------------------------+

6. 
Installed from main https://github.com/Oneflow-Inc/diffusers#egg=onediff


Also, I emailed you guys for oneflow enterprise? Is there any way to speed things up ? Would love to hop on a call ASAP

**Comment by jackalcooper** [comment]
> Also, I emailed you guys for oneflow enterprise? Is there any way to speed things up ? Would love to hop on a call ASAP

i replied you with two emails. maybe they got filtered or archived?

**Comment by strint** [comment]
@ErwannMillon 

> diffusers version: 0.24.0.dev0

We have updated yesterday for diffusers > 0.19.x. Please do these updates:
1. update oneflow community with:
```
python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu122
```

2. update onediff to the latest main branch
https://github.com/Oneflow-Inc/diffusers/tree/main
commit id: cc844a46749a4c988cbc759783648e63e8f59b85

Then try:
```
python examples/text_to_image_sdxl.py
```

I tried the diffusers 0.24.0 on my RTX 3090 just now, and it passed.

**Comment by ErwannMillon** [comment]
Oneflow works fine. I can do hundreds to thousands of inferences, before I finally hit a segfault out of nowhere.

**Comment by strint** [comment]
> Oneflow works fine. I can do hundreds to thousands of inferences, before I finally hit a segfault out of nowhere.

Let's arrange a  meeting to get this clear. Did you get the email from my colleague?

**Comment by strint** [comment]
This issue is too old to follow and will be closed. Feel free to reopen it and continue.

**Comment by bigmover** [comment]
> This issue is too old to follow and will be closed. Feel free to reopen it and continue.

@strint  The issue has any updated? How can people solve it  when have the problem?

**Comment by niehen6174** [comment]
> Oneflow works fine. I can do hundreds to thousands of inferences, before I finally hit a segfault out of nowhere.

Hi, Have you solved this problem? I have the same problem.
