### ISSUE TITLE
ModuleNotFoundError: No module named 'oneflow.framework.args_tree'

### ISSUE THREAD

**Issue by bingnoi** [Oneflow-Inc/onediff#395]
严格遵循了你们的教程 安装了oneflow onediff 为啥还是会报这个错误 python版本也是3.10了 还有其他可能的原因吗 或者有定位错误的方法么

**Comment by bingnoi** [comment]
之前的问题解决了 又爆了新的错误 
`python: /home/ci-user/manylinux-cache-dir/release/cu117/build/oneflow/ir/llvm_monorepo-src/llvm/include/llvm/Support/CommandLine.h:846: void llvm::cl::parser<DataType>::addLiteralOption(llvm::StringRef, const DT&, llvm::StringRef) [with DT = llvm::FunctionPass* (*)(); DataType = llvm::FunctionPass* (*)()]: Assertion `findOption(Name) == Values.size() && "Option already exists!"' failed.`

**Comment by bingnoi** [comment]
已经都试过了 oneflow-0.9 onediff-0.11.0.dev0 cuda11.6 还是一样的错误

**Comment by hjchen2** [comment]
那您跑我们的sd1.5的example会报错么，https://github.com/Oneflow-Inc/onediff/blob/main/examples/text_to_image.py

**Comment by bingnoi** [comment]
你好 还是不行 会报这个错ModuleNotFoundError: No module named 'oneflow.framework.args_tree'  但是我去安装的oneflow目录下去看了 确实不存在 args_tree这个文件 请问问题是出在哪里了呢

**Comment by strint** [comment]
https://github.com/Oneflow-Inc/onediff/tree/main#install-from-source

应该是需要安装下最新的 oneflow

**Comment by hjchen2** [comment]
oneflow-0.9这个版本是错的，正确安装应该是0.9.1版本的。你可以重新安装一下oneflow，把安装过程截图发到这里来，可能的原因有：一是你的python版本过低，我们只支持py3.7到oy3.10；二是cuda版本过低，我们要求cuda版本>=11.8

**Comment by bingnoi** [comment]
对的 问题是cuda版本过低 我的是cuda11.6 建议明确说明一下这个版本要求 我确实没在主页readme上看到这个要求 谢谢你们的帮助！

**Comment by bigmover** [comment]
> oneflow-0.9这个版本是错的，正确安装应该是0.9.1版本的。你可以重新安装一下oneflow，把安装过程截图发到这里来，可能的原因有：一是你的python版本过低，我们只支持py3.7到py3.10；二是cuda版本过低，我们要求cuda版本>=11.8

@hjchen2  请问 cuda 11.7版本有办法可以支持？
