### ISSUE TITLE
编译图时，输入参数转换错误

### ISSUE THREAD

**Issue by zhangvia** [Oneflow-Inc/onediff#400]
我的模型的输入包含了一个int型的参数，在__build_io中，经过args_tree.mapleaf之后，int型变量变成了None，而其他tensor，list都是正常类型。这是bug吗，还是不支持int型输入？
## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS: ubuntu20.04
- OneFlow version (run `python3 -m oneflow --doctor`):0.9.1+cu118
- Python version:3.9
- CUDA driver version:11.8
- GPU models:
- Other info:

**Comment by strint** [comment]
@zhangvia 

参考这里说明，安装下最新的 oneflow，应该可以解决这个问题：https://github.com/Oneflow-Inc/onediff#install-from-source

这个是才合并的

**Comment by zhangvia** [comment]
问题已解决，多谢
