### ISSUE TITLE
Login required?

### ISSUE THREAD

**Issue by norv2001** [Oneflow-Inc/onediff#415]
Hi, I'm trying to pull the repo but I get the following error:

docker pull oneflowinc/comfyui-onediff:latest
Error response from daemon: pull access denied for oneflowinc/comfyui-onediff, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

How to fix? Thank you!

**Comment by jackalcooper** [comment]
it is include in our paid plan
please send an email to caishenghang@oneflow.org, to tell us about your use case
