### ISSUE TITLE
Support dynamic batching?

### ISSUE THREAD

**Issue by Xiang-cd** [Oneflow-Inc/onediff#432]
跑batchsize=1后再跑batchsize=10就奔溃了

**Comment by strint** [comment]
If you are using onediff community version, you can open this to support  dynamic batch( which cost some time to re-compile)

```
oneflow_compile(model, options={"all_dynamic":True})
```

We have a low cost experimental solution in onediff enterprise edition: https://github.com/Oneflow-Inc/onediff?tab=readme-ov-file#business-inquiry-on-onediff-enterprise-edition

**Comment by Xiang-cd** [comment]
谢谢

**Comment by kopyl** [comment]
@strint still error...
<img width="515" alt="image" src="https://github.com/Oneflow-Inc/onediff/assets/17604849/4d784c7b-da7d-47cd-837f-622a8793c745">


Here is how i do it:

```
!pip install git+https://github.com/kopyl/oneflow-diffusers.git
!pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/master_open_source/cu118
!pip install git+https://github.com/huggingface/diffusers.git
!pip install transformers
!pip install scipy


from diffusers import StableDiffusionPipeline, UNet2DConditionModel, AutoencoderKL
import torch
from PIL import Image
import math
from diffusers import logging
import numpy as np
logging.set_verbosity_error()

from onediff.infer_compiler import oneflow_load_compiled, oneflow_compile
from onediff.schedulers import EulerDiscreteScheduler
from onediff.optimization import rewrite_self_attention


pipeline = StableDiffusionPipeline.from_pretrained(
    "/workspace",
    torch_dtype=torch.float16,
    safety_checker=None,
).to("cuda")

rewrite_self_attention(pipeline.unet)

pipeline.unet = oneflow_compile(pipeline.unet, options={"all_dynamic":True})

generator = torch.Generator(device="cuda")
generator.seed()
generation = pipeline(prompt='picture icon', height=256, width=256, num_inference_steps=40, guidance_scale=10, generator=generator, num_images_per_prompt=9)
images = generation.images
image = images[0]
print(generator.initial_seed())
image
```

**Comment by kopyl** [comment]
@strint seems like it's sone new update or something. In the official version (`!pip install git+https://github.com/Oneflow-Inc/onediff.git`) it works fine.

But gives only +15it/s to the speed. Very very slow. SIngle-batch with Oneflow gives me 80-110it/s.

Is there any way to make it same fast? Maybe specify strict batch?

**Comment by kopyl** [comment]
@strint i can do this with `options={"size": 9}`

But with size 9 I don't see any improvement. With size 2 it's the same fast as with single-batch-sisze... But with size 4 it gets worse (72 it/s). With size 8 it's almost the same slow as size 9...

**Comment by kopyl** [comment]
With original stable diffusion pipeline with no patched unet there is almost no degradation in speed.

Is there any way to make it same fast on RTX 4090? I can get multiple RTX 4090 if it can help to speed things up.

But with that very small improvement it does not make sense to bring
1. Additional time to load compiled graph from file
2. + around 2 GB to the Docker image size...

**Comment by kopyl** [comment]
@strint by the way, my images are always 256x256. Can this help speed generations up?

**Comment by strint** [comment]
> @strint by the way, my images are always 256x256. Can this help speed generations up if I compile the graph specifically with this size?

You need dynamic batch size, but fixed height and width?

**Comment by strint** [comment]
> But gives only +15it/s to the speed. Very very slow. SIngle-batch with Oneflow gives me 80-110it/s.

When you enable `options={"all_dynamic":True}`, each time it got a  new input shape(new  batch size), it takes some time to  compile for the new input shape.

```
# input0 shape = [1, h, w]
run(input0)  # compile and run

# input1 shape = [1, h, w]
run(input1)  # run (input shape has been compiled)

# input2 shape = [2, h, w]
run(input2)  # compile and run(new shape)

# input3 shape = [1, h, w]
run(input3)  # run (input shape has been compiled)

# input4 shape = [2, h, w]
run(input4)  # run (input shape has been compiled)
```

**Comment by kopyl** [comment]
@strint nope, i just need fixed batch size (always 9) and fixed width and height.

Can it help speed up image generations/

**Comment by strint** [comment]
> @strint nope, i just need fixed batch size (always 9) and fixed width and height.
> 
> Can it help speed up image generations?

batch size 1: 6.59it/s

batch size 4: 1.63it/s

1.63 * 4 = 6.52

So bigger batch size will not make it faster as I know. Note in my case, when run with batch size 1, the GPU-Util is already 97%~99%.

If your GPU-Util is not full with batch size 1, increasing batch size is helpful.

**Comment by kopyl** [comment]
@strint oh, i did not even think about it, thank you very much... So only getting a more powerful GPU can speed batched generations, correct?

**Comment by strint** [comment]
> @strint oh, i did not even think about it, thank you very much... So only getting a more powerful GPU can speed batched generations, correct?

Yes.

I'm on 3090, batch size 1 makes the GPU-Util 97%~99%.

If you are on 4090 or  A100, you can try to increase the batch size to make the GPU-Util 97%~99%.
