### ISSUE TITLE
When loading the graph, the following node types were not found: ModelSpeedup

### ISSUE THREAD

**Issue by BenDes21** [Oneflow-Inc/onediff#437]
Hi there, correctly setup onediff and copy paste onediff_comfy_nodes into custom_nodes but the node ModelSpeedup is not found. Any solution ? Thanks

**Comment by slimanibenbadis** [comment]
> Are there more error messages about the problem?
> 
> Such as code error stack?

Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes\__init__.py", line 2, in <module>
    from ._config import _USE_UNET_INT8
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes\_config.py", line 15, in <module>
    import register_comfy  # load plugins
    ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes\infer_compiler_registry\register_comfy\__init__.py", line 1, in <module>
    from onediff.infer_compiler import register
ModuleNotFoundError: No module named 'onediff'

Here is the main cause.

**Comment by BenDes21** [comment]
C:\Users\Admin\Documents\Stable diffusion\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:25: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\Stable diffusion\ComfyUI\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Admin\Documents\Stable diffusion\ComfyUI\ComfyUI\custom_nodes\onediff_comfy_nodes\__init__.py", line 2, in <module>
    from ._config import _USE_UNET_INT8
  File "C:\Users\Admin\Documents\Stable diffusion\ComfyUI\ComfyUI\custom_nodes\onediff_comfy_nodes\_config.py", line 15, in <module>
    import register_comfy  # load plugins
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Documents\Stable diffusion\ComfyUI\ComfyUI\custom_nodes\onediff_comfy_nodes\infer_compiler_registry\register_comfy\__init__.py", line 1, in <module>
    from onediff.infer_compiler import register
ModuleNotFoundError: No module named 'onediff'

Cannot import C:\Users\Admin\Documents\Stable diffusion\ComfyUI\ComfyUI\custom_nodes\onediff_comfy_nodes module for custom nodes: No module named 'onediff'

**Comment by strint** [comment]
> > Are there more error messages about the problem?
> > Such as code error stack?
> 
> Traceback (most recent call last): File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes__init__.py", line 2, in from ._config import _USE_UNET_INT8 File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes_config.py", line 15, in import register_comfy # load plugins ^^^^^^^^^^^^^^^^^^^^^ File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes\infer_compiler_registry\register_comfy__init__.py", line 1, in from onediff.infer_compiler import register ModuleNotFoundError: No module named 'onediff'
> 
> Here is the main cause.

So you are using OneDiff in Windows or  WSL?

**Comment by strint** [comment]
> C:\Users\Admin\Documents\Stable diffusion\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:25: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly") Traceback (most recent call last): File "C:\Users\Admin\Documents\Stable diffusion\ComfyUI\ComfyUI\nodes.py", line 1800, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "C:\Users\Admin\Documents\Stable diffusion\ComfyUI\ComfyUI\custom_nodes\onediff_comfy_nodes__init__.py", line 2, in from ._config import _USE_UNET_INT8 File "C:\Users\Admin\Documents\Stable diffusion\ComfyUI\ComfyUI\custom_nodes\onediff_comfy_nodes_config.py", line 15, in import register_comfy # load plugins ^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Admin\Documents\Stable diffusion\ComfyUI\ComfyUI\custom_nodes\onediff_comfy_nodes\infer_compiler_registry\register_comfy__init__.py", line 1, in from onediff.infer_compiler import register ModuleNotFoundError: No module named 'onediff'
> 
> Cannot import C:\Users\Admin\Documents\Stable diffusion\ComfyUI\ComfyUI\custom_nodes\onediff_comfy_nodes module for custom nodes: No module named 'onediff'

So you are using OneDiff in Windows or WSL?

**Comment by strint** [comment]
We only support Linux for the moment.

If you want to use OneDiff in Windows, please use it under WSL.

**Comment by slimanibenbadis** [comment]
> > > Are there more error messages about the problem?
> > > Such as code error stack?
> > 
> > 
> > Traceback (most recent call last): File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes__init__.py", line 2, in from ._config import _USE_UNET_INT8 File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes_config.py", line 15, in import register_comfy # load plugins ^^^^^^^^^^^^^^^^^^^^^ File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\onediff_comfy_nodes\infer_compiler_registry\register_comfy__init__.py", line 1, in from onediff.infer_compiler import register ModuleNotFoundError: No module named 'onediff'
> > Here is the main cause.
> 
> So you are using OneDiff in Windows or WSL?

Oh that's why, I did not see it mentioned on your documentation or installation guide. 

Do you have an estimated timeframe when a compatibility for Windows will be added ?

Thanks.

**Comment by strint** [comment]
> Oh that's why, I did not see it mentioned on your documentation or installation guide.

Thanks for mention, we added the note: https://github.com/Oneflow-Inc/onediff?tab=readme-ov-file#install-from-source-or-using-in-docker

> Do you have an estimated timeframe when a compatibility for Windows will be added ?

Now we mainly support Server side usage. We will discuss this.
