### ISSUE TITLE
OneFlow Stable Diffusion 运行

### ISSUE THREAD

**Issue by jackalcooper** [Oneflow-Inc/onediff#5]
https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion

**Comment by jackalcooper** [comment]
> 请问one flow版本的SD最低支持多少显存的GPU做推理？

fp16 模型，8GB。

**Comment by baymin0220** [comment]
oneflow 和xformers可以联合使用来提高速度的吗？谢谢

**Comment by shangguanshiyuan** [comment]
> oneflow 和xformers可以联合使用来提高速度的吗？谢谢
你好，OneFlow发布的Stable Diffusion的实现里已经包含了xformers中的优化，所以不需要额外引入，也不支持联合使用。

**Comment by cvv-student** [comment]
注意到第一次运行会编译静态图，消耗的时候特别多，相比编译后的图变慢了4～5倍，oneflow如果做落地部署，也需要花这么长的时间编译图么？

**Comment by strint** [comment]
> oneflow如果做落地部署，也需要花这么长的时间编译图么？

You can reference here to do offline compile: https://github.com/Oneflow-Inc/diffusers/issues/75#issuecomment-1418789541

@cvv-student

**Comment by zhaozhongyu** [comment]
安装完之后提示This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow

**Comment by shangguanshiyuan** [comment]
> 安装完之后提示This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow

你好，您是在哪个环境下安装的oneflow？目前oneflow只支持linux，不支持windows和macos，目前预编译的安装包只包含了x86 cpu和cuda gpu。

**Comment by zhaozhongyu** [comment]
难怪, 我在windows上安装的

**Comment by Doolfly** [comment]
> 

Linux 的版本有要求吗？ 我在Oracle Unbreakable Linux 7 上也安装不下去

**Comment by strint** [comment]
This issue is too old to follow and will be closed. Feel free to reopen it and continue.
