### ISSUE TITLE
support for SD v2 depth2image

### ISSUE THREAD

**Issue by tripathiarpan20** [Oneflow-Inc/onediff#68]
Requesting support for SD v2.0 depth2image model:
[pipeline_stable_diffusion_depth2img.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_depth2img.py)

**Comment by strint** [comment]
This issue is too old to follow and will be closed. Feel free to reopen it and continue.
