### ISSUE TITLE
实现超长prompt输入以及prompt加权计算支持

### ISSUE THREAD

**Issue by CrazyBoyM** [Oneflow-Inc/onediff#74]
参考 https://github.com/huggingface/diffusers/blob/main/examples/community/lpw_stable_diffusion.py  
可以实现大于77token的prompt输入，以及使用（）[]等为prompt中的元素进行加权强调，很实用。  
请求支持一下StableDiffusionLongPromptWeightingPipeline的Oneflow框架运行版本。

**Comment by strint** [comment]
This issue is too old to follow and will be closed. Feel free to reopen it and continue.
