### ISSUE TITLE
Increasing the batch size may not improve performance, is that expected?

### ISSUE THREAD

**Issue by yuikns** [Oneflow-Inc/onediff#88]
We use `OneFlowStableDiffusionPipeline` to run a pretrained model. It's a huge performance improvement over the original.
 
However if I want to increase the batch size to improve the average performance per image, this does not work. The gpu memory usage increased, but the average time consuming even increased as well.

I tried using a list of prompts (`batchlized_prompt = [ p for p in range(num_images_per_prompt))`),

or pass in the `num_images_per_prompt` parameter. 

According to the callback, all the images are generating parallel, but the total time could never reduced. 

Any advice is super appreciated.

**Comment by jackalcooper** [comment]
what is your expected performance (compared to single image per prompt)? Could you give us some numbers on certain GPU models? Thank you.

**Comment by yuikns** [comment]
@jackalcooper I am using v100 to generate 768x768 images, step = 50

If I generate 1 image, it will take around 5.89 seconds.
If I generate 4 images ( set `num_images_per_prompt` up to 4), and the total time is 23.59 seconds. 

The GPU memory usage is 4 times, and the time consumption is a linear increase.

Is there any change to make the total time to generate 4 images a bit less than 4 * 1 images?  is 15 seconds a possible value?

**Comment by yuikns** [comment]
Apologize for the late reply. Since I was using v0.9.0, when I got your comment, oneflow v0.9.1 was released and there are some code migration work.
I updated the code and dependencies, and compared the performance, and the above numbers are the latest one.

**Comment by luvWY** [comment]
> 

Hi, when I set num_images_per_prompt up to 4, I expected to get 4 generated images. But I only got one. Why? I

**Comment by yuikns** [comment]
@luvWY Had you calculated the time elapsed? if the total time cost was 4 times than the origin, maybe you truncated the result list i guess?

**Comment by luvWY** [comment]
> I calculated the time elapsed. They are the same! Why "num_images_per_prompt" didn't work?

`
import time
prompt = 'Dogs'
height=512
width=512
start_time = time.time()
num_images_per_prompt =10
images = pipe(prompt,num_inference_steps=5, guidance_scale=2.5,height=height, width=width, num_images_per_prompt= num_images_per_prompt ).images
end_time = time.time()
print("current time: ",end_time-start_time)
`

**Comment by strint** [comment]
batch size 1: 6.59it/s

batch size 4: 1.63it/s

1.63 * 4 = 6.52

So bigger batch size will not make it faster as I know.

Note in my case, when run with batch size 1, the GPU-Util is already 97%~99%.

If your GPU-Util is not full with batch size 1, increasing batch size is helpful.
