### ISSUE TITLE
When will fused_multi_head_attention_inference support attn mask?

### ISSUE THREAD

**Issue by dingjingzhen** [Oneflow-Inc/onediff#92]
### Description

hi，
     I have a stable diffusion project that requires attn mask and would like to use oneflow for acceleration. I see that xformers already supports it, but it's still too slow compared to oneflow.So when will fused_multi_head_attention_inference support attn mask?

**Comment by liujuncheng** [comment]
We are currently working on adding attn mask support to fused_multi_head_attention_inference, and expect to have it available in the next one to two weeks.

**Comment by dingjingzhen** [comment]
> We are currently working on adding attn mask support to fused_multi_head_attention_inference, and expect to have it available in the next one to two weeks.

Thanks for the reply, if there is an update please inform me in time
